// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvtxZ67AEBu5K9tsek2jGD9yBXti7P4Pw',
    appId: '1:279925360239:android:22870a1d6ce6a4e3386f9a',
    messagingSenderId: '279925360239',
    projectId: 'flutter-test-2-6aa0c',
    databaseURL: 'https://flutter-test-2-6aa0c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-test-2-6aa0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVkqS8UMb_sKJf0nzYeb_kuLCBlEwKcj0',
    appId: '1:279925360239:ios:9fcfcb1606ac05ea386f9a',
    messagingSenderId: '279925360239',
    projectId: 'flutter-test-2-6aa0c',
    databaseURL: 'https://flutter-test-2-6aa0c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-test-2-6aa0c.appspot.com',
    iosBundleId: 'com.example.chat',
  );
}
